#ifndef EVIO_H_
#define EVIO_H_

#define SUCC 0
#define UNEXPECT_ERROR -1
#define REPEAT_PROCESS -100
#define HAVENT_SEGMENT -101
#define TIME_INVERSE -200
#define HUGE_GAP -201
#define OUT_OF_RANGE -202
#define STATIONARY 666
#define STATIONARY_EVENTS 10
#define STATIONARY_IMU_GYRO 0.04
#define STATIONARY_IMU_ACC 0.3
#define HEIGHT 480
#define WIDTH 640
#define ENVELOPE_K 40
#define GRID_SIZE 20
#define TIME_OFFSET 0.4

#define DOWNSAMPLE_SIZE 40000

#define DBSCAN_RESERVE 40
#define DBSCAN_DIS 8
#define DBSCAN_COUNT 15
#define DBSCAN_MIN_SIZE 40
#define DBSCAN_DEVIDE_POLARITY 1
#define DBSCAN_DFS_DEPTH 0

#define USE_GT 1



#endif
